In [1]:
# Install a library to connect to the database server
%pip install psycopg2-binary

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.10-cp313-cp313-macosx_14_0_arm64.whl.metadata (4.9 kB)
Downloading psycopg2_binary-2.9.10-cp313-cp313-macosx_14_0_arm64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 17.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.10
Note: you may need to restart the kernel to use updated packages.

In [2]:
import psycopg2

In [9]:
# Establish a connection to the PostgreSQL server
# ใช้ในการสร้าง connection ไปยัง PostgreSQL server
conn = psycopg2.connect(
        host="localhost",   # The hostname of your PostgreSQL server
        dbname="osm",   # The name of the database you want to connect to
        user="admin",    # The username that you have set up for the database
        password="root",  # The password for your user
        port=5433           # Port number which PostgreSQL server is listening on
    )
print("Successfully connected to the database!")

Successfully connected to the database!

In [10]:
# สร้าง cursor เพื่อห่อหุ้มคำสั่ง SQL ที่เราจะใช้ในการจัดการฐานข้อมูล
cur = conn.cursor()

In [12]:
# เช่น เรียกคำว่า SELECT เพื่อ query ข้อมูลทั้งหมดจากตาราง account
cur.execute("SELECT * FROM organizations")

In [13]:
# while there are rows left to be fetched
row = cur.fetchone()
while row is not None:
    print(row)  # print the current row
    row = cur.fetchone()  # fetch the next row

(1, 'FAB0d41d5b5d22c', 'Ferrell LLC', 'https://price.net/', 'Papua New Guinea', 'Horizontal empowering knowledgebase', '1990', 'Plastics', 3498)
(2, '6A7EdDEA9FaDC52', 'Mckinney, Riley and Day', 'http://www.hall-buchanan.info/', 'Finland', 'User-centric system-worthy leverage', '2015', 'Glass / Ceramics / Concrete', 4952)
(3, '0bFED1ADAE4bcC1', 'Hester Ltd', 'http://sullivan-reed.com/', 'China', 'Switchable scalable moratorium', '1971', 'Public Safety', 5287)
(4, '2bFC1Be8a4ce42f', 'Holder-Sellers', 'https://becker.com/', 'Turkmenistan', 'De-engineered systemic artificial intelligence', '2004', 'Automotive', 921)
(5, '9eE8A6a4Eb96C24', 'Mayer Group', 'http://www.brewer.com/', 'Mauritius', 'Synchronized needs-based challenge', '1991', 'Transportation', 7870)
(6, 'cC757116fe1C085', 'Henry-Thompson', 'http://morse.net/', 'Bahamas', 'Face-to-face well-modulated customer loyalty', '1992', 'Primary / Secondary Education', 4914)
(7, '219233e8aFF1BC3', 'Hansen-Everett', 'https://www.kidd.org/', 'Pakistan', 'Seamless disintermediate collaboration', '2018', 'Publishing Industry', 7832)
(8, 'ccc93DCF81a31CD', 'Mcintosh-Mora', 'https://www.brooks.com/', 'Heard Island and McDonald Islands', 'Centralized attitude-oriented capability', '1970', 'Import / Export', 4389)
(9, '0B4F93aA06ED03e', 'Carr Inc', 'http://ross.com/', 'Kuwait', 'Distributed impactful customer loyalty', '1996', 'Plastics', 8167)
(10, '738b5aDe6B1C6A5', 'Gaines Inc', 'http://sandoval-hooper.com/', 'Uzbekistan', 'Multi-lateral scalable protocol', '1997', 'Outsourcing / Offshoring', 9698)
(11, 'AE61b8Ffebbc476', 'Kidd Group', 'http://www.lyons.com/', 'Bouvet Island (Bouvetoya)', 'Proactive foreground paradigm', '2001', 'Primary / Secondary Education', 7473)
(12, 'eb3B7D06cCdD609', 'Crane-Clarke', 'https://www.sandoval.com/', 'Denmark', 'Front-line clear-thinking encryption', '2014', 'Food / Beverages', 9011)
(13, '8D0c29189C9798B', 'Keller, Campos and Black', 'https://www.garner.info/', 'Liberia', 'Ameliorated directional emulation', '2020', 'Museums / Institutions', 2862)
(14, 'D2c91cc03CA394c', 'Glover-Pope', 'http://www.silva.biz/', 'United Arab Emirates', 'Persevering contextually-based approach', '2013', 'Medical Practice', 9079)
(15, 'C8AC1eaf9C036F4', 'Pacheco-Spears', 'https://aguilar.com/', 'Sweden', 'Secured logistical synergy', '1984', 'Maritime', 769)
(16, 'b5D10A14f7a8AfE', 'Hodge-Ayers', 'http://www.archer-elliott.com/', 'Honduras', 'Future-proofed radical implementation', '1990', 'Facilities Services', 8508)
(17, '68139b5C4De03B4', 'Bowers, Guerra and Krause', 'http://www.carrillo-nicholson.com/', 'Uganda', 'De-engineered transitional strategy', '1972', 'Primary / Secondary Education', 6986)
(18, '5c2EffEfdba2BdF', 'Mckenzie-Melton', 'http://montoya-thompson.com/', 'Hong Kong', 'Reverse-engineered heuristic alliance', '1998', 'Investment Management / Hedge Fund / Private Equity', 4589)
(19, 'ba179F19F7925f5', 'Branch-Mann', 'http://www.lozano.com/', 'Botswana', 'Adaptive intangible frame', '1999', 'Architecture / Planning', 7961)
(20, 'c1Ce9B350BAc66b', 'Weiss and Sons', 'https://barrett.com/', 'Korea', 'Sharable optimal functionalities', '2011', 'Plastics', 5984)
(21, '8de40AC4e6EaCa4', 'Velez, Payne and Coffey', 'http://burton.com/', 'Luxembourg', 'Mandatory coherent synergy', '1986', 'Wholesale', 5010)
(22, 'Aad86a4F0385F2d', 'Harrell LLC', 'http://www.frey-rosario.com/', 'Guadeloupe', 'Reverse-engineered mission-critical moratorium', '2018', 'Construction', 2185)
(23, '22aC3FFd64fD703', 'Eaton, Reynolds and Vargas', 'http://www.freeman.biz/', 'Monaco', 'Self-enabling multi-tasking process improvement', '2014', 'Luxury Goods / Jewelry', 8987)
(24, '5Ec4C272bCf085c', 'Robbins-Cummings', 'http://donaldson-wilkins.com/', 'Belgium', 'Organic non-volatile hierarchy', '1991', 'Pharmaceuticals', 5038)
(25, '5fDBeA8BB91a000', 'Jenkins Inc', 'http://www.kirk.biz/', 'South Africa', 'Front-line systematic help-desk', '2002', 'Insurance', 1215)
(26, 'dFfD6a6F9AC2d9C', 'Greene, Benjamin and Novak', 'http://www.kent.net/', 'Romania', 'Centralized leadingedge moratorium', '2012', 'Museums / Institutions', 4941)
(27, '4B217cC5a0674C5', 'Dickson, Richmond and Clay', 'http://everett.com/', 'Czech Republic', 'Team-oriented tangible complexity', '1980', 'Real Estate / Mortgage', 3122)
(28, '88b1f1cDcf59a37', 'Prince-David', 'http://thompson.com/', 'Christmas Island', 'Virtual holistic methodology', '1970', 'Banking / Mortgage', 1046)
(29, 'f9F7bBCAEeC360F', 'Ayala LLC', 'http://www.zhang.com/', 'Philippines', 'Open-source zero administration hierarchy', '2021', 'Legal Services', 7664)
(30, '7Cb3AeFcE4Ba31e', 'Rivas Group', 'https://hebert.org/', 'Australia', 'Open-architected well-modulated capacity', '1998', 'Logistics / Procurement', 4155)
(31, 'ccBcC32adcbc530', 'Sloan, Mays and Whitehead', 'http://lawson.com/', 'Chad', 'Face-to-face high-level conglomeration', '1997', 'Civil Engineering', 365)
(32, 'f5afd686b3d05F5', 'Durham, Allen and Barnes', 'http://chan-stafford.org/', 'Zimbabwe', 'Synergistic web-enabled framework', '1993', 'Mechanical or Industrial Engineering', 6135)
(33, '38C6cfC5074Fa5e', 'Fritz-Franklin', 'http://www.lambert.com/', 'Nepal', 'Automated 4thgeneration website', '1972', 'Hospitality', 4516)
(34, '5Cd7efccCcba38f', 'Burch-Ewing', 'http://cline.net/', 'Taiwan', 'User-centric 4thgeneration system engine', '1981', 'Venture Capital / VC', 7443)
(35, '9E6Acb51e3F9d6F', 'Glass, Barrera and Turner', 'https://dunlap.com/', 'Kyrgyz Republic', 'Multi-channeled 3rdgeneration open system', '2020', 'Utilities', 2610)
(36, '4D4d7E18321eaeC', 'Pineda-Cox', 'http://aguilar.org/', 'Bolivia', 'Fundamental asynchronous capability', '2010', 'Human Resources / HR', 1312)
(37, '485f5d06B938F2b', 'Baker, Mccann and Macdonald', 'http://www.anderson-barker.com/', 'Kenya', 'Cross-group user-facing focus group', '2013', 'Legislative Office', 1638)
(38, '19E3a5Bf6dBDc4F', 'Cuevas-Moss', 'https://dodson-castaneda.net/', 'Guatemala', 'Extended human-resource intranet', '1994', 'Music', 9995)
(39, '6883A965c7b68F7', 'Hahn PLC', 'http://newman.com/', 'Belarus', 'Organic logistical leverage', '2012', 'Electrical / Electronic Manufacturing', 3715)
(40, 'AC5B7AA74Aa4A2E', 'Valentine, Ferguson and Kramer', 'http://stuart.net/', 'Jersey', 'Centralized secondary time-frame', '1997', 'Non - Profit / Volunteering', 3585)
(41, 'decab0D5027CA6a', 'Arroyo Inc', 'https://www.turner.com/', 'Grenada', 'Managed demand-driven website', '2006', 'Writing / Editing', 9067)
(42, 'dF084FbBb613eea', 'Walls LLC', 'http://www.reese-vasquez.biz/', 'Cape Verde', 'Self-enabling fresh-thinking installation', '1989', 'Investment Management / Hedge Fund / Private Equity', 1678)
(43, 'A2D89Ab9bCcAd4e', 'Mitchell, Warren and Schneider', 'https://fox.biz/', 'Trinidad and Tobago', 'Enhanced intangible time-frame', '2021', 'Capital Markets / Hedge Fund / Private Equity', 3816)
(44, '77aDc905434a49f', 'Prince PLC', 'https://www.watts.com/', 'Sweden', 'Profit-focused coherent installation', '2016', 'Individual / Family Services', 7645)
(45, '235fdEFE2cfDa5F', 'Brock-Blackwell', 'http://www.small.com/', 'Benin', 'Secured foreground emulation', '1986', 'Online Publishing', 7034)
(46, '1eD64cFe986BBbE', 'Walton-Barnett', 'https://ashley-schaefer.com/', 'Western Sahara', 'Right-sized clear-thinking flexibility', '2001', 'Luxury Goods / Jewelry', 1746)
(47, 'CbBbFcdd0eaE2cF', 'Bartlett-Arroyo', 'https://cruz.com/', 'Northern Mariana Islands', 'Realigned didactic function', '1976', 'Civic / Social Organization', 3987)
(48, '49aECbDaE6aBD53', 'Wallace, Madden and Morris', 'http://www.blevins-fernandez.biz/', 'Germany', 'Persistent real-time customer loyalty', '2016', 'Pharmaceuticals', 9443)
(49, '7b3fe6e7E72bFa4', 'Berg-Sparks', 'https://cisneros-love.com/', 'Canada', 'Stand-alone static implementation', '1974', 'Arts / Crafts', 2073)
(50, 'c6DedA82A8aef7E', 'Gonzales Ltd', 'http://bird.com/', 'Tonga', 'Managed human-resource policy', '1988', 'Consumer Goods', 9069)
(51, '7D9FBF85cdC3871', 'Lawson and Sons', 'https://www.wong.com/', 'French Southern Territories', 'Compatible analyzing intranet', '2021', 'Arts / Crafts', 3527)
(52, '7dd18Fb7cB07b65', 'Mcguire, Mcconnell and Olsen', 'https://melton-briggs.com/', 'Korea', 'Profound client-server frame', '1988', 'Printing', 8445)
(53, 'EF5B55FadccB8Fe', 'Charles-Phillips', 'https://bowman.com/', "Cote d'Ivoire", 'Monitored client-server implementation', '2012', 'Mental Health Care', 3450)
(54, 'f8D4B99e11fAF5D', 'Odom Ltd', 'https://www.humphrey-hess.com/', "Cote d'Ivoire", 'Advanced static process improvement', '2012', 'Management Consulting', 1825)
(55, 'e24D21BFd3bF1E5', 'Richard PLC', 'https://holden-coleman.net/', 'Mayotte', 'Object-based optimizing model', '1971', 'Broadcast Media', 4942)
(56, 'B9BdfEB6D3Ca44E', 'Sampson Ltd', 'https://blevins.com/', 'Cayman Islands', 'Intuitive local adapter', '2005', 'Farming', 1418)
(57, '2a74D6f3D3B268e', 'Cherry, Le and Callahan', 'https://waller-delacruz.biz/', 'Nigeria', 'Universal human-resource collaboration', '2017', 'Entertainment / Movie Production', 7202)
(58, 'Bf3F3f62c8aBC33', 'Cherry PLC', 'https://www.avila.info/', 'Marshall Islands', 'Persistent tertiary website', '1980', 'Plastics', 8245)
(59, 'aeBe26B80a7a23c', 'Melton-Nichols', 'https://kennedy.com/', 'Palau', 'User-friendly clear-thinking productivity', '2021', 'Legislative Office', 8741)
(60, 'aAeb29ad43886C6', 'Potter-Walsh', 'http://thomas-french.org/', 'Turkey', 'Optional non-volatile open system', '2008', 'Human Resources / HR', 6923)
(61, 'bD1bc6bB6d1FeD3', 'Freeman-Chen', 'https://mathis.com/', 'Timor-Leste', 'Phased next generation adapter', '1973', 'International Trade / Development', 346)
(62, 'EB9f456e8b7022a', 'Soto Group', 'https://norris.info/', 'Vietnam', 'Enterprise-wide executive installation', '1988', 'Business Supplies / Equipment', 9097)
(63, 'Dfef38C51D8DAe3', 'Poole, Cruz and Whitney', 'https://reed.info/', 'Reunion', 'Balanced analyzing groupware', '1978', 'Marketing / Advertising / Sales', 2992)
(64, '055ffEfB2Dd95B0', 'Riley Ltd', 'http://wiley.com/', 'Brazil', 'Optional exuding superstructure', '1986', 'Textiles', 9315)
(65, 'cBfe4dbAE1699da', 'Erickson, Andrews and Bailey', 'https://www.hobbs-grant.com/', 'Eritrea', 'Vision-oriented secondary project', '2014', 'Consumer Electronics', 7829)
(66, 'fdFbecbadcdCdf1', 'Wilkinson, Charles and Arroyo', 'http://hunter-mcfarland.com/', 'United States Virgin Islands', 'Assimilated 24/7 archive', '1996', 'Building Materials', 602)
(67, '5DCb8A5a5ca03c0', 'Floyd Ltd', 'http://www.whitney.com/', 'Falkland Islands (Malvinas)', 'Function-based fault-tolerant concept', '2017', 'Public Relations / PR', 2911)
(68, 'ce57DCbcFD6d618', 'Newman-Galloway', 'https://www.scott.com/', 'Luxembourg', 'Enhanced foreground collaboration', '1987', 'Information Technology / IT', 3934)
(69, '5aaD187dc929371', 'Frazier-Butler', 'https://www.daugherty-farley.info/', 'Northern Mariana Islands', 'Persistent interactive circuit', '1972', 'Outsourcing / Offshoring', 5130)
(70, '902D7Ac8b6d476b', 'Newton Inc', 'https://www.richmond-manning.info/', 'Netherlands Antilles', 'Fundamental stable info-mediaries', '1976', 'Military Industry', 563)
(71, '32BB9Ff4d939788', 'Duffy-Levy', 'https://www.potter.com/', 'Guernsey', 'Diverse exuding installation', '1982', 'Wireless', 6146)
(72, 'adcB0afbE58bAe3', 'Wagner LLC', 'https://decker-esparza.com/', 'Uruguay', 'Reactive attitude-oriented toolset', '1987', 'International Affairs', 6874)
(73, 'dfcA1c84AdB61Ac', 'Mccall-Holmes', 'http://www.dean.com/', 'Benin', 'Object-based value-added database', '2009', 'Legal Services', 696)
(74, '208044AC2fe52F3', 'Massey LLC', 'https://frazier.biz/', 'Suriname', 'Configurable zero administration Graphical User Interface', '1986', 'Accounting', 5004)
(75, 'f3C365f0c1A0623', 'Hicks LLC', 'http://alvarez.biz/', 'Pakistan', 'Quality-focused client-server Graphical User Interface', '1970', 'Computer Software / Engineering', 8480)
(76, 'ec5Bdd3CBAfaB93', 'Cole, Russell and Avery', 'http://www.blankenship.com/', 'Mongolia', 'De-engineered fault-tolerant challenge', '2000', 'Law Enforcement', 7012)
(77, 'DDB19Be7eeB56B4', 'Cummings-Rojas', 'https://simon-pearson.com/', 'Svalbard & Jan Mayen Islands', 'User-centric modular customer loyalty', '2012', 'Financial Services', 7529)
(78, 'dd6CA3d0bc3cAfc', 'Beasley, Greene and Mahoney', 'http://www.petersen-lawrence.com/', 'Togo', 'Extended content-based methodology', '1976', 'Religious Institutions', 869)
(79, 'A0B9d56e61070e3', 'Beasley, Sims and Allison', 'http://burke.info/', 'Latvia', 'Secured zero tolerance hub', '1972', 'Facilities Services', 6182)
(80, 'cBa7EFe5D05Adaf', 'Crawford-Rivera', 'https://black-ramirez.org/', 'Cuba', 'Persevering exuding budgetary management', '1999', 'Online Publishing', 7805)
(81, 'Ea3f6D52Ec73563', 'Montes-Hensley', 'https://krueger.org/', 'Liechtenstein', 'Multi-tiered secondary productivity', '2009', 'Printing', 8433)
(82, 'bC0CEd48A8000E0', 'Velazquez-Odom', 'https://stokes.com/', 'Djibouti', 'Streamlined 6thgeneration function', '2002', 'Alternative Dispute Resolution', 4044)
(83, 'c89b9b59BC4baa1', 'Eaton-Morales', 'https://www.reeves-graham.com/', 'Micronesia', 'Customer-focused explicit frame', '1990', 'Capital Markets / Hedge Fund / Private Equity', 7013)
(84, 'FEC51bce8421a7b', 'Roberson, Pennington and Palmer', 'http://www.keith-fisher.com/', 'Cameroon', 'Adaptive bi-directional hierarchy', '1993', 'Telecommunications', 5571)
(85, 'e0E8e27eAc9CAd5', 'George, Russo and Guerra', 'https://drake.com/', 'Sweden', 'Centralized non-volatile capability', '1989', 'Military Industry', 2880)
(86, 'B97a6CF9bf5983C', 'Davila Inc', 'https://mcconnell.info/', 'Cocos (Keeling) Islands', 'Profit-focused dedicated frame', '2017', 'Consumer Electronics', 2215)
(87, 'a0a6f9b3DbcBEb5', 'Mays-Preston', 'http://www.browning-key.com/', 'Mali', 'User-centric heuristic focus group', '2006', 'Military Industry', 5786)
(88, '8cC1bDa330a5871', 'Pineda-Morton', 'https://www.carr.com/', 'United States Virgin Islands', 'Grass-roots methodical info-mediaries', '1991', 'Printing', 6168)
(89, 'ED889CB2FE9cbd3', 'Huang and Sons', 'https://www.bolton.com/', 'Eritrea', 'Re-contextualized dynamic hierarchy', '1981', 'Semiconductors', 7484)
(90, 'F4Dc1417BC6cb8f', 'Gilbert-Simon', 'https://www.bradford.biz/', 'Burundi', 'Grass-roots radical parallelism', '1973', 'Newspapers / Journalism', 1927)
(91, '7ABc3c7ecA03B34', 'Sampson-Griffith', 'http://hendricks.org/', 'Benin', 'Multi-layered composite paradigm', '1972', 'Textiles', 3881)
(92, '4e0719FBE38e0aB', 'Miles-Dominguez', 'http://www.turner.com/', 'Gibraltar', 'Organized empowering forecast', '1996', 'Civic / Social Organization', 897)
(93, 'dEbDAAeDfaed00A', 'Rowe and Sons', 'https://www.simpson.org/', 'El Salvador', 'Balanced multimedia knowledgebase', '1978', 'Facilities Services', 8172)
(94, '61BDeCfeFD0cEF5', 'Valenzuela, Holmes and Rowland', 'https://www.dorsey.net/', 'Taiwan', 'Persistent tertiary focus group', '1999', 'Transportation', 1483)
(95, '4e91eD25f486110', 'Best, Wade and Shepard', 'https://zimmerman.com/', 'Zimbabwe', 'Innovative background definition', '1991', 'Gambling / Casinos', 4873)
(96, '0a0bfFbBbB8eC7c', 'Holmes Group', 'https://mcdowell.org/', 'Ethiopia', 'Right-sized zero tolerance focus group', '1975', 'Photography', 2988)
(97, 'BA6Cd9Dae2Efd62', 'Good Ltd', 'http://duffy.com/', 'Anguilla', 'Reverse-engineered composite moratorium', '1971', 'Consumer Services', 4292)
(98, 'E7df80C60Abd7f9', 'Clements-Espinoza', 'http://www.flowers.net/', 'Falkland Islands (Malvinas)', 'Progressive modular hub', '1991', 'Broadcast Media', 236)
(99, 'AFc285dbE2fEd24', 'Mendez Inc', 'https://www.burke.net/', 'Kyrgyz Republic', 'User-friendly exuding migration', '1993', 'Education Management', 339)
(100, 'e9eB5A60Cef8354', 'Watkins-Kaiser', 'http://www.herring.com/', 'Togo', 'Synergistic background access', '2009', 'Financial Services', 2785)

### Install sqlalchemy and psycopg2 to connect PostgreSQL with Pandas ###

In [17]:
%pip install sqlalchemy psycopg2
%pip install pandas

Collecting sqlalchemy
  Using cached SQLAlchemy-2.0.36-cp313-cp313-macosx_11_0_arm64.whl.metadata (9.7 kB)
Collecting psycopg2
  Using cached psycopg2-2.9.10.tar.gz (385 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Downloading SQLAlchemy-2.0.36-cp313-cp313-macosx_11_0_arm64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 30.5 MB/s eta 0:00:00
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (pyproject.toml) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.10-cp313-cp313-macosx_10_13_universal2.whl size=243467 sha256=47c805c15d98a7a8330fd2a72f2b7347993db5df7b682675d5152af55565c5bb
  Stored in directory: /Users/kraiwit/Library/Caches/pip/wheels/d1/02/6b/6fab072a7ac365814e6d6217fef5525fa5ac3c64204a418040
Successfully built psycopg2
Installing collected packages: typing-extensions, psycopg2, sqlalchemy
Successfully installed psycopg2-2.9.10 sqlalchemy-2.0.36 typing-extensions-4.12.2
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kraiwit/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /Users/kraiwit/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import sqlalchemy
from sqlalchemy import Table, Column, String, MetaData

# สร้าง engine ที่ใช้ในการเชื่อมต่อกับ PostgreSQL server
# postgresql://[account]:[password]@localgos:[port]/[dbname]
engine = sqlalchemy.create_engine('postgresql://admin:root@localhost:5433/osm')

In [21]:
import pandas as pd
import numpy as np

df = pd.read_sql('select * from organizations', con=engine) # use engine from previous cell

### View overall data ###

In [22]:
df

,idx,oid,oname,website,country,description,founded,industry,num_employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
...,...,...,...,...,...,...,...,...,...
95,96,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,97,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,100,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [23]:
df.dtypes

idx               int64
oid              object
oname            object
website          object
country          object
description      object
founded          object
industry         object
num_employees     int64
dtype: object

In [24]:
df.head()

,idx,oid,oname,website,country,description,founded,industry,num_employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870

In [25]:
df.tail()

,idx,oid,oname,website,country,description,founded,industry,num_employees
95,96,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,97,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,100,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

In [26]:
df.columns

Index(['idx', 'oid', 'oname', 'website', 'country', 'description', 'founded',
       'industry', 'num_employees'],
      dtype='object')

In [27]:
df.describe()

              idx  num_employees
count  100.000000     100.000000
mean    50.500000    4964.860000
std     29.011492    2850.859799
min      1.000000     236.000000
25%     25.750000    2741.250000
50%     50.500000    4941.500000
75%     75.250000    7558.000000
max    100.000000    9995.000000

In [28]:
# What is the index of each data record?
df

,idx,oid,oname,website,country,description,founded,industry,num_employees
0,1,FAB0d41d5b5d22c,Ferrell LLC,https://price.net/,Papua New Guinea,Horizontal empowering knowledgebase,1990,Plastics,3498
1,2,6A7EdDEA9FaDC52,"Mckinney, Riley and Day",http://www.hall-buchanan.info/,Finland,User-centric system-worthy leverage,2015,Glass / Ceramics / Concrete,4952
2,3,0bFED1ADAE4bcC1,Hester Ltd,http://sullivan-reed.com/,China,Switchable scalable moratorium,1971,Public Safety,5287
3,4,2bFC1Be8a4ce42f,Holder-Sellers,https://becker.com/,Turkmenistan,De-engineered systemic artificial intelligence,2004,Automotive,921
4,5,9eE8A6a4Eb96C24,Mayer Group,http://www.brewer.com/,Mauritius,Synchronized needs-based challenge,1991,Transportation,7870
...,...,...,...,...,...,...,...,...,...
95,96,0a0bfFbBbB8eC7c,Holmes Group,https://mcdowell.org/,Ethiopia,Right-sized zero tolerance focus group,1975,Photography,2988
96,97,BA6Cd9Dae2Efd62,Good Ltd,http://duffy.com/,Anguilla,Reverse-engineered composite moratorium,1971,Consumer Services,4292
97,98,E7df80C60Abd7f9,Clements-Espinoza,http://www.flowers.net/,Falkland Islands (Malvinas),Progressive modular hub,1991,Broadcast Media,236
98,99,AFc285dbE2fEd24,Mendez Inc,https://www.burke.net/,Kyrgyz Republic,User-friendly exuding migration,1993,Education Management,339
99,100,e9eB5A60Cef8354,Watkins-Kaiser,http://www.herring.com/,Togo,Synergistic background access,2009,Financial Services,2785

##### Indices of the above example assigned automatically according to the order of fetched data. However, we can create index for each data record also. #####

In [29]:
df_test = pd.DataFrame([1, 2, 3, 4, 5], index=[100, 29, 234, 1, 150],
                  columns=['A'])

In [30]:
df_test

     A
100  1
29   2
234  3
1    4
150  5

In [31]:
df_test.sort_index()

     A
1    4
29   2
100  1
150  5
234  3

In [ ]:
df

In [ ]:
df.sort_values(by='balance', ascending=False)

In [ ]:
df.sort_index()

### Selection ###

#### Getitem ([]) ####

In [32]:
df['balance']

KeyError: 'balance'

In [ ]:
df.balance

In [ ]:
df

In [ ]:
# Get the first and second rows from the dataframe
df[0:2]

#### Selection by label ####

In [ ]:
df.loc[:,["account_number", "balance"]]    # all rows, only with columns: account_number and balance

In [ ]:
df.loc[0:4]

In [ ]:
df

In [ ]:
df.loc[1:4,["account_number", "balance"]] # [rows 1-4, only "account_number" and "balance" columns]

In [ ]:
df

#### Selection by position ####

In [ ]:
df

In [ ]:
df.iloc[3]

In [ ]:
df

In [ ]:
df.iloc[3:5, 0:2]  # rows 3 and 4 and columns 0 and 1

In [ ]:
df.iloc[[1, 2, 4], [0, 2]]

In [ ]:
df.iloc[1:3, :]

In [ ]:
df

In [ ]:
df.iat[1, 1]

In [ ]:
df.iat[1,2]

#### Boolean indexing ####

In [ ]:
df["balance"] > 100

In [ ]:
df[df["balance"] > 100]

In [ ]:
df

In [ ]:
df[df['branch_name'] == 'B']

In [ ]:
df[df['branch_name'].isin(['B', 'F'])]

In [ ]:
%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df['balance'].plot(kind="bar");

In [ ]:
df2 = pd.read_sql('select a.branch_name, sum(a.balance) from account a group by a.branch_name', con=engine)

In [ ]:
df2['sum'].plot(kind="bar");